spring:
  datasource:
    url: jdbc:mysql://b8rtjzrosuobna9islsi-mysql.services.clever-cloud.com:3306/b8rtjzrosuobna9islsi
    username: uhotjopfpqowkusn
    password: hh9bYIEUFIPR6trTCws1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    com.miapp: DEBUG

